#!/bin/bash
set -e

# SpeechD-NG Installer

CONFIG_DIR="$HOME/.config/speechd-ng"
CONFIG_FILE="$CONFIG_DIR/Speech.toml"

echo "========================================"
echo "   SpeechD-NG Installer (v0.7.1)"
echo "========================================"

# 1. Detect Distribution
echo "[*] Detecting Distribution..."
if [ -f /etc/debian_version ]; then
    DISTRO="debian"
    echo "    Detected: Debian/Ubuntu based"
elif [ -f /etc/redhat-release ]; then
    DISTRO="redhat"
    echo "    Detected: Fedora/RHEL based"
else
    echo "    Unknown distribution. Proceeding with manual package selection?"
    exit 1
fi

# 2. Locate Package
echo "[*] Locating Package..."
if [ "$DISTRO" == "debian" ]; then
    PKG=$(find dist -name "speechserverdaemon_*_amd64.deb" | sort -V | tail -n1)
    if [ -z "$PKG" ]; then
        echo "Error: No .deb package found in dist/"
        exit 1
    fi
    INSTALL_CMD="sudo apt-get install -y ./$PKG"
    # Ensure dependencies
    sudo apt-get update
    sudo apt-get install -y espeak-ng python3 libasound2
elif [ "$DISTRO" == "redhat" ]; then
    PKG=$(find dist -name "speechserverdaemon-*.x86_64.rpm" | sort -V | tail -n1)
    if [ -z "$PKG" ]; then
        echo "Error: No .rpm package found in dist/"
        exit 1
    fi
    INSTALL_CMD="sudo dnf install -y ./$PKG"
fi

echo "    Found: $PKG"
read -p "    Install this package? [Y/n] " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]] && [[ -n $REPLY ]]; then
    echo "Aborting installation."
    exit 1
fi

# 3. Install Package
echo "[*] Installing Package..."
$INSTALL_CMD

# 4. Configuration
echo "[*] Configuration Wizard"
mkdir -p "$CONFIG_DIR"

# Defaults
WAKE_WORD="hey_jarvis"
ENABLE_AI="false"
STT_BACKEND="vosk"

# Wake Word
echo
echo "--- Wake Word Selection ---"
echo "1) Hey Jarvis (default)"
echo "2) Alexa"
echo "3) Computer"
echo "4) Custom (enter manually)"
read -p "Select [1-4]: " ww_choice
case $ww_choice in
    2) WAKE_WORD="alexa" ;;
    3) WAKE_WORD="computer" ;;
    4) read -p "Enter custom wake word (snake_case): " WAKE_WORD ;;
    *) WAKE_WORD="hey_jarvis" ;;
esac

# AI
echo
echo "--- AI Integration ---"
read -p "Enable Ollama integration? (requires local Ollama) [y/N]: " ai_choice
if [[ $ai_choice =~ ^[Yy]$ ]]; then
    ENABLE_AI="true"
fi

# STT
echo
echo "--- Speech to Text ---"
echo "1) Vosk (Local, Embedded)"
echo "2) Wyoming (Remote/Home Assistant)"
read -p "Select [1-2]: " stt_choice
if [ "$stt_choice" == "2" ]; then
    STT_BACKEND="wyoming"
fi

# Write Config
echo "[*] Writing configuration to $CONFIG_FILE..."
cat > "$CONFIG_FILE" <<EOF
# SpeechD-NG Configuration
# Generated by install.sh on $(date)

[speech]
# Audio/TTS
playback_volume = 1.0
memory_size = 10
vad_sensitivity = "medium"
vad_speech_threshold = 0.5
rate_limit_tts = 30 # per minute
rate_limit_listen = 30

# Wake Word
wake_word = "$WAKE_WORD"
wake_word_sensitivity = 0.5

# Advanced
log_level = "info"
enable_timestamps = true

[ai]
enable_ai = $ENABLE_AI
system_prompt = "You are a helpful assistant."
passive_confidence_threshold = 0.7

[stt]
backend = "$STT_BACKEND" # vosk or wyoming
wyoming_host = "127.0.0.1"
wyoming_port = 10300
wyoming_model = "tiny-int8"
wyoming_auto_start = false

EOF

# 5. Service
echo "[*] Enabling Service..."
systemctl --user daemon-reload
systemctl --user enable --now speechd-ng

echo "========================================"
echo "   Installation Complete!"
echo "========================================"
echo
echo "Your configuration has been saved to:"
echo "   $CONFIG_FILE"
echo
echo "You can edit this file manually at any time to change settings."
echo "To restart the service after changes, run:"
echo "   systemctl --user restart speechd-ng"
echo
echo "Enjoy!"
